FROM node:22.17.0-alpine

WORKDIR /app

RUN corepack enable pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm i --frozen-lockfile --prod=false

COPY tsconfig.json ./
COPY src/payload.config.ts ./src/
COPY src/payload-types.ts ./src/
COPY src/collections/ ./src/collections/
COPY src/blocks/ ./src/blocks/
COPY src/utilities/ ./src/utilities/
COPY src/migrations/ ./src/migrations/

ENV NODE_ENV=production
ENV CI=true

CMD ["pnpm", "run", "payload", "migrate"]
